### ISSUE TITLE
Add support for "LOL-CHALLENGES-V1"

### ISSUE THREAD

**Issue by ItzDerock** [fightmegg/riot-rate-limiter#352]
Currently, if you try to make a request to the new challenges paths (for example `/lol/challenges/v1/challenges/config`) you will get `unsupported region: na1 or method: null`

**Comment by OllieJennings** [comment]
This should be done by #394 apologies for taking so long

**Comment by OllieJennings** [comment]
Will be publishing the latest version of RiotAPI with these new endpoints tomorrow
