### ISSUE TITLE
Request never ends when MatchList endpoint returns a 404

### ISSUE THREAD

**Issue by vkaelin** [fightmegg/riot-rate-limiter#52]
Hi!
When I try to add the ``beginIndex`` field and there is no more match returned by the Riot's API, my code never ends.
No error is throw despite the fact that Riot is returning a 404.
Here are the logs of my application:

```
riotratelimiter:main Request: https://na1.api.riotgames.com/lol/match/v4/matchlists/by-account/AGzqwU_OQkvutSMe2LmMy_g6And1by0RA7JWOBvWbLXsuA?beginIndex=200 region: na1 method: MATCH.GET_MATCHLIST_BY_ACCOUNT +42ms
  riotratelimiter:queue na1 MATCH.GET_MATCHLIST_BY_ACCOUNT Event triggered: received { RECEIVED: 1, QUEUED: 0, RUNNING: 0, EXECUTING: 0 } +3ms
  riotratelimiter:queue na1 MATCH.GET_MATCHLIST_BY_ACCOUNT Event triggered: queued { RECEIVED: 0, QUEUED: 1, RUNNING: 0, EXECUTING: 0 } +12ms
  riotratelimiter:queue na1 MATCH.GET_MATCHLIST_BY_ACCOUNT Draining 1602361073878 { RECEIVED: 0, QUEUED: 1, RUNNING: 0, EXECUTING: 0 } +0ms
  riotratelimiter:queue na1 MATCH.GET_MATCHLIST_BY_ACCOUNT Drained 1602361073878 { RECEIVED: 0, QUEUED: 1, RUNNING: 0, EXECUTING: 0 } +16ms
```

Thanks!

**Comment by OllieJennings** [comment]
@vkaelin Thanks for this,  just got back and will look into fixing this today.

**Comment by OllieJennings** [comment]
@vkaelin I have added some tests for this. It seems like there is no issue, can you please look at the tests in the linked PR and make sure your code is running it correctly.

If you are still seeing issues, would you mind pasting some of your code?

**Comment by vkaelin** [comment]
@OllieJennings Thanks for this! Will try to make a repo this weekend when I have some time!

**Comment by OllieJennings** [comment]
Hey @vkaelin am just going to close this issue, but if you do find any issue please feel free to re-open
